### ISSUE TITLE
Scarecrows spawning in random spots

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#498] opened 2014-12-22 15:31 UTC
On respawn they'll spawn in their correct place though.

**Comment by twostars** [comment] 2015-01-03 15:20
Nope, couldn't reproduce this one either. We'll need to check this on alpha after a restart.

**Comment by maxmenten** [comment] 2015-01-03 15:47
Can't reproduce this on Alpha either, closing this for now.

**Closed by maxmenten** 2015-01-03 15:47 UTC
Labels: bug, database, linux-specific
